# Generated by Django 3.0.5 on 2020-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ManyToManyField(blank=True, to='users.Sport'),
        ),
    ]
