# Generated by Django 3.0.5 on 2020-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
