# Generated by Django 3.0.5 on 2020-05-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='captain',
            new_name='manager',
        ),
    ]
