# Generated by Django 3.0.5 on 2020-05-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
        ('teams', '0004_auto_20200521_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Sport'),
            preserve_default=False,
        ),
    ]
