# Generated by Django 3.0.5 on 2020-05-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
        ('teams', '0006_auto_20200521_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Sport'),
        ),
    ]
