# Generated by Django 3.0.5 on 2020-05-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
        ('teams', '0008_auto_20200521_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to='users.UserProfile'),
        ),
    ]
