# Generated by Django 3.0.5 on 2020-04-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_area_sport_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(max_length=164, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport',
            field=models.CharField(max_length=164, unique=True),
        ),
    ]
