# Generated by Django 3.0.5 on 2020-04-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200421_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_complete',
        ),
    ]
