# Generated by Django 3.0.5 on 2020-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200426_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='communication',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sport',
            field=models.ManyToManyField(to='users.Sport'),
        ),
    ]
