# Generated by Django 3.0.5 on 2020-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('time', models.DateTimeField(blank=True)),
                ('location', models.CharField(max_length=256)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('map_location', models.CharField(blank=True, max_length=16)),
                ('banner', models.ImageField(blank=True, upload_to='media')),
                ('poster', models.ImageField(blank=True, upload_to='media')),
                ('payment_required', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('event_created', models.DateTimeField(auto_now=True)),
                ('registrants', models.ManyToManyField(blank=True, related_name='registrants', to='users.UserProfile')),
            ],
        ),
    ]
