# Generated by Django 3.0.5 on 2020-05-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtype_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostname',
            name='logo',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
