# Generated by Django 3.0.5 on 2020-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200512_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
