# Generated by Django 3.0.5 on 2020-05-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200428_1442'),
        ('events', '0006_auto_20200512_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='team_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='users.UserProfile')),
                ('members', models.ManyToManyField(blank=True, related_name='team_member', to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='registered_teams', to='events.Team'),
        ),
    ]
