# Generated by Django 3.0.5 on 2020-05-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200518_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='map_location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='events',
            name='max_team',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='min_team',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
