# Generated by Django 3.0.5 on 2020-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200519_1114'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='registered_teams', to='teams.Team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
